chenxiaolong/BCR

README.md
app/build.gradle.kts
app/src/main/java/com/chiller3/bcr/Permissions.kt
app/src/main/java/com/chiller3/bcr/RecorderInCallService.kt
app/src/main/java/com/chiller3/bcr/RecorderThread.kt

There was only one API call, `AudioFormat.getFrameSizeInBytes()`, that required at least API 29. It's trivial enough to reimplement that function manually.
Fixes: #6

Add support for API 28

---

app/src/main/java/com/chiller3/bcr/RecorderThread.kt

With this change, the timestamps in the filenames will match the timestamps in Android's call log exactly.
Issue: #3

RecorderThread: Use call creation time instead of recording time

---

app/src/main/java/com/chiller3/bcr/RecorderThread.kt

This is based on CNAP only and does not perform lookups against the user's contacts. Note that only the initial CNAP value at the time the call becomes active is used. CNAP changes are ignored.
Issue: #3

RecorderThread: Add caller display name to the filename for incoming calls

---

app/build.gradle.kts
app/src/main/java/com/chiller3/bcr/SettingsActivity.kt

This adds the revision count since the last tag and the abbreviated git commit to the version name. These components are added only when HEAD is not already a tag.

Add git commit info to version name

---

app/src/main/java/com/chiller3/bcr/RecorderThread.kt

MediaCodec's FLAC encoder does not write the final duration to the
STREAMINFO metadata block. The streaming nature of the API makes that
impossible. Instead, when the recording completes, BCR will find the
STREAMINFO block and update the total frame count field manually.
This fixes seeking in audio players that don't try to guess the length
of the audio file.
Fixes: #19

RecorderThread: Write duration to FLAC STREAMINFO metadata block

---

app/src/main/res/values-tr/strings.xml

Add Turkish translations from @fnldstntn

---

app/build.gradle.kts

By adding the whole directory, the update metadata would be included as well.

build.gradle.kts: Only include update-binary and updater-script from the magisk directory

---

app/build.gradle.kts

Specifically because of the third field, which is an ObjectId instance.
Since only the first field is used by the updateJson tasks, only add
that as an input.

build.gradle.kts: gitVersionTriple is not serializable

---

app/src/main/java/com/chiller3/bcr/RecorderThread.kt
app/src/main/java/com/chiller3/bcr/codec/AacCodec.kt
app/src/main/java/com/chiller3/bcr/codec/Codec.kt
app/src/main/java/com/chiller3/bcr/codec/CodecParamType.kt
app/src/main/java/com/chiller3/bcr/codec/Container.kt
app/src/main/java/com/chiller3/bcr/codec/FlacCodec.kt
app/src/main/java/com/chiller3/bcr/codec/FlacContainer.kt
app/src/main/java/com/chiller3/bcr/codec/MediaMuxerContainer.kt
app/src/main/java/com/chiller3/bcr/codec/OpusCodec.kt

This commit adds the initial framework for allowing the configuration of
output codecs. There are three codec choices available:
* FLAC: (default) lossless, compression level 0-8
* OGG/Opus: lossy, bitrate 6-510kbps, Android 10+ only
* M4A/AAC: lossy, HE-AAC bitrate 24-32kbps, AAC-LC bitrate 32-128kbps
While all three codecs are implemented, RecorderThread is currently
hardcoded to use the default. The next step is to save and load the
codec configuration from SharedPreferences and the finally add the user
interface.
Issue: #21

Add initial support for configurable codecs

---

README.md

It turns out Android's Storage Access Framework doesn't support cloud
storage when using ACTION_OPEN_DOCUMENT_TREE for selecting a folder.
https://issuetracker.google.com/issues/135636079
Closes: #30

README.md: Remove mention of cloud storage

---

app/src/main/java/com/chiller3/bcr/Preferences.kt
app/src/main/java/com/chiller3/bcr/RecorderThread.kt
app/src/main/java/com/chiller3/bcr/SettingsActivity.kt
app/src/main/java/com/chiller3/bcr/codec/AacCodec.kt
app/src/main/java/com/chiller3/bcr/codec/Codec.kt
app/src/main/java/com/chiller3/bcr/codec/Codecs.kt
app/src/main/java/com/chiller3/bcr/codec/FlacCodec.kt
app/src/main/java/com/chiller3/bcr/codec/OpusCodec.kt
app/src/main/res/values/strings.xml
app/src/main/res/xml/root_preferences.xml

This PR implements the initial preference UI for the output format as well as having `RecorderThread` use the selected codec (and codec parameter) for encoding.
Codec configuration is not yet possible. That will be implemented in a future PR.
Issue: #21

Add initial preference for output encoding format

---

README.md
app/src/main/java/com/chiller3/bcr/CodecBottomSheetFragment.kt
app/src/main/java/com/chiller3/bcr/Preferences.kt
app/src/main/java/com/chiller3/bcr/SettingsActivity.kt
app/src/main/java/com/chiller3/bcr/codec/AacCodec.kt
app/src/main/java/com/chiller3/bcr/codec/Codec.kt
app/src/main/java/com/chiller3/bcr/codec/CodecParamType.kt
app/src/main/java/com/chiller3/bcr/codec/Codecs.kt
app/src/main/java/com/chiller3/bcr/codec/FlacCodec.kt
app/src/main/java/com/chiller3/bcr/codec/OpusCodec.kt
app/src/main/res/layout/codec_bottom_sheet.xml
app/src/main/res/layout/codec_bottom_sheet_button.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/root_preferences.xml

The configuration is implemented as a bottom sheet that appears when
clicking the new output format preferences. Changes are applied
immediately and per-codec configuration values are preserved when
switching codecs.
Issue: #21

Add encoder configuration UI

---

README.md
app/src/main/java/com/chiller3/bcr/codec/Codecs.kt

Codecs: Set OGG/Opus as the default codec

---

app/magisk/updates/release/changelog.txt
app/src/main/java/com/chiller3/bcr/RecorderInCallService.kt
app/src/main/java/com/chiller3/bcr/RecorderThread.kt

This commit updates BCR's own logging to redact:
* Phone number
* CNAP/Caller ID
* Contact name
from log messages. Note that this is not foolproof because Android
itself (eg. MediaProvider) will log the full filename.

Redact sensitive information from logcat

---

app/build.gradle.kts
app/magisk/updates/release/changelog.txt
app/proguard-rules.pro

Obfuscation makes nearly no difference in size for this project. No
reason to make life harder for folks who want to inspect the compiled
binaries.

Enable minification of release builds without obfuscation

---

app/magisk/updates/release/changelog.txt
app/src/main/java/com/chiller3/bcr/FormatBottomSheetFragment.kt
app/src/main/java/com/chiller3/bcr/Preferences.kt
app/src/main/java/com/chiller3/bcr/RecorderThread.kt
app/src/main/java/com/chiller3/bcr/SettingsActivity.kt
app/src/main/java/com/chiller3/bcr/format/SampleRates.kt
app/src/main/res/layout/format_bottom_sheet.xml
app/src/main/res/values/strings.xml

The default will remain the audio source's native sample rate.

Add support for configurable sample rate

---

app/src/main/java/com/chiller3/bcr/RecorderThread.kt

This was previously disabled due to incorrect troubleshooting of an
issue where the `c2.android.flac.encoder` component would crash during
recording. It turns out the crash was caused by incorrect math:
inputTimestamp += frames * 1000000 / audioRecord.sampleRate
`frames` and `1000000` are both 32-bit integers, so the multiplication
result overflowed and caused `inputTimestamp` (a 64-bit integer) to
accumulate negative values, which would crash the encoder. This bug was
inadvertently fixed during refactoring in commit
3d3eb821800a114a8768539650cbdfd3a0bf17c9.
This commit reenables the submission of timestamps to MediaCodec. To
avoid accumulated error due to integer division when the microseconds
per sample count is not perfectly divisible, the recording loop will
keep track of the total …

RecorderThread: Send input timestamps to MediaCodec encoders

---

app/src/main/java/com/chiller3/bcr/RecorderThread.kt
app/src/main/java/com/chiller3/bcr/format/AacFormat.kt
app/src/main/java/com/chiller3/bcr/format/Encoder.kt
app/src/main/java/com/chiller3/bcr/format/FlacContainer.kt
app/src/main/java/com/chiller3/bcr/format/FlacFormat.kt
app/src/main/java/com/chiller3/bcr/format/Format.kt
app/src/main/java/com/chiller3/bcr/format/MediaCodecEncoder.kt
app/src/main/java/com/chiller3/bcr/format/MediaMuxerContainer.kt
app/src/main/java/com/chiller3/bcr/format/OpusFormat.kt
app/src/main/java/com/chiller3/bcr/format/PassthroughEncoder.kt
app/src/main/java/com/chiller3/bcr/format/WaveContainer.kt
app/src/main/java/com/chiller3/bcr/format/WaveFormat.kt

Previously, for passthrough recording, AudioRecord would record into a
100ms sized buffer (at the specified sample rate). For encoded
recording, it would record directly into MediaCodec's buffers, which may
or may not be sized appropriately.
This commit unifies the buffering scheme for both types of recording to
use a buffer twice the size of `AudioRecord.getMinBufferSize`. It also
introduces the `Encoder` abstraction to allow dealing with passthrough
and MediaCodec the same way.

Rework buffering mechanism for recording

---

app/src/main/java/com/chiller3/bcr/Preferences.kt
app/src/main/java/com/chiller3/bcr/RecorderInCallService.kt
app/src/main/java/com/chiller3/bcr/RecorderThread.kt
app/src/main/java/com/chiller3/bcr/SettingsActivity.kt
app/src/main/res/xml/root_preferences.xml

The hidden debug mode can be enabled in release builds by long pressing the BCR version number. The version will change from `release` to `release+debugmode`. In debug mode, each recording will create an additional `<filename>.log.txt` file.
Debug builds always have debug mode enabled and it cannot be disabled there.

Add hidden debug mode for release builds

---

app/src/main/java/com/chiller3/bcr/format/Container.kt
app/src/main/java/com/chiller3/bcr/format/FlacContainer.kt
app/src/main/java/com/chiller3/bcr/format/MediaMuxerContainer.kt
app/src/main/java/com/chiller3/bcr/format/WaveContainer.kt

There's no internal state, so an abstract class is not needed.

Container: Change to an interface

---

app/src/main/java/com/chiller3/bcr/FormatBottomSheetFragment.kt
app/src/main/java/com/chiller3/bcr/RecorderThread.kt
app/src/main/java/com/chiller3/bcr/SettingsActivity.kt
app/src/main/java/com/chiller3/bcr/format/SampleRates.kt
app/src/main/res/values-es/strings.xml
app/src/main/res/values-tr/strings.xml
app/src/main/res/values/strings.xml

This helps absorb some of the impact of encoding slowdowns at the expense of latency, which doesn't matter for recording purposes.
This also necessitates the removal of the native sample rate option because it would require initializing AudioRecord twice: the first time to detect the sample rate and the second time to set the desired sample-rate-dependent buffer size. It's better to explicitly specify a sample rate anyway because the native sample rate may not be compatible with all codecs (eg. Opus does not support 44100Hz).

Significantly increase AudioRecord's internal buffer size

---

app/src/main/java/com/chiller3/bcr/RecorderInCallService.kt
app/src/main/java/com/chiller3/bcr/RecorderThread.kt

This commit changes RecorderThread's behavior to first record to the
default/fallback output directory and then move to the user-specified
target directory when the recording is complete.
This avoids issues where writing to the SAF-provided file descriptor
sometimes has several hundren millisecond latencies, causing
AudioRecord's internal buffer to overrun. On some devices, this happens
even when the SAF directory is on internal storage. The root cause of
why the SAF-provided file descriptor is slow is unknown. Perhaps the
FUSE filesystem at /sdcard does some additional checks on write with SAF
paths compared to the Context.getExternalFilesDir() path.
Fixes: #39
Fixes: #54

RecorderThread: Record to internal storage first

---

app/src/main/java/com/chiller3/bcr/RecorderThread.kt

When the call ends, everything still remaining in AudioRecord's internal
buffer is lost because there's no way to read the remaining bytes after
recording is stopped. With 20x the buffer size on eg. a device with a
1920 byte minimum buffer size and a sample rate of 8000 Hz, this may
cause 2.4 seconds of audio at the end of the call to be lost.
This commit should not have a negative effect since the large buffer
size was meant to address buffer overruns and the root cause of that
problem was fixed in #72.

RecorderThread: Make AudioRecord internal buffer less excessively large

---

app/src/main/java/com/chiller3/bcr/SettingsActivity.kt

DocumentsContract.findDocumentPath() may sometimes crash with a
permission error when passed a children document URI after an app
upgrade, even though the app still has valid persisted URI permissions.
Instead, just parse the URI manually. The format of SAF URIs hasn't
changed across the versions of Android that BCR supports.

SettingsActivity: Fix possible crash when showing friendly path

---

README.md
app/src/main/java/com/chiller3/bcr/Permissions.kt
app/src/main/java/com/chiller3/bcr/SettingsActivity.kt

The contacts permission is used to add the contact name to the output
filenames. The permission prompt will only be shown the first time call
recording is enabled. If the user chooses to not allow the permission,
but wants to allow it later, they will have to do so via the system
settings.
Fixes: #78
Fixes: #80

SettingsActivity: Prompt for optional contacts permission on first enable

---

README.md

The feature was removed in version 1.11 because Android has no way of
reporting the native sample rate without actually starting a recording.
Andd to start a recording with a good buffer size, the sample rate is
required, leading to a catch-22.
Issue: #110

README.md: Remove mention of native sample rate

---

app/src/main/java/com/chiller3/bcr/RecorderInCallService.kt
app/src/main/java/com/chiller3/bcr/RecorderThread.kt

When receiving a call from a private number, the `Call.Details` instance provided by Android has a null `Uri` for the handle. This isn't documented in the Android SDK.
This commit fixes the issue by adding a null check and also changes the error handling so that early failures (during creation of RecorderThread) will still result in an error notification being shown.
Fixes: #111

Fix crash when receiving call from a private number

---

README.md
app/magisk/update-binary

This will install BCR directly into the system partition. With this installation method, Magisk is not involved at all.
Fixes: #128

Add support for flashing via recovery

---

app/magisk/update-binary

update-binary: Explicitly remount as writable; Ignore cleanup failures due to ENOENT

---

app/src/main/java/com/chiller3/bcr/RecorderThread.kt

The output files should generally be unique, but that's not guaranteed. Without truncation, the output files may potentially be corrupted due to the presence of old data at the end.
Issue: #143

RecorderThread: Open output files with O_TRUNC

---

app/src/main/java/com/chiller3/bcr/RecorderThread.kt

The logcat implementation calls fflush() only when it's printing log messages to stdout.

RecorderThread: Redirect stdout of logcat instead of using -f

---

app/src/main/java/com/chiller3/bcr/RecorderThread.kt

The file descriptor ownership and lifetimes are not clearly documented for Java's standard library classes, like FileOutputStream and FileChannel. Since we always have file descriptors to local files, just call sendfile directly. ParcelFileDescriptor.close() will always be responsible for closing the file descriptors.

RecorderThread: Copy files using sendfile syscall

---

app/src/main/java/com/chiller3/bcr/RecorderInCallService.kt
app/src/main/java/com/chiller3/bcr/RecorderThread.kt

On older Samsung firmware, the telephony framework fails to notify `InCallService` implementations about call disconnections. This doesn't just happen with BCR. It affects Samsung's own apps too, like Knox's `InCallServiceImpl`.
Due to this bug, none of the following callbacks are called when a call ends:
* `Call.Callback.onStateChanged` with `Call.STATE_DISCONNECTING` or `Call.STATE_DISCONNECTED`
* `Call.Callback.onCallDestroyed`
* `InCallService.onCallRemoved`
However, it does happen to call `Call.Callback.onDetailsChanged` when the call state transitions to `Call.STATE_DISCONNECTED` (which doesn't happen with AOSP).
This commit reworks `RecorderInCallService` to keep track of calls better in the face of these firmware bugs. A call's lifetime begins when `InCallService.onCallAdded` is …

RecorderInCallService: Improve end-of-call detection

---

app/src/main/java/com/chiller3/bcr/RecorderThread.kt

On Samsung devices, when a call ends, `AudioRecord.read()` blocks until another call becomes active, which prevents recordings from stopping at the correct time. This behavior does not happen in AOSP.
To work around this, use non-blocking reads with a sleep interval of the `AudioRecord` minimum buffer size. This gives the recording loop a chance to check if recording has been cancelled.
Issue: #143

RecorderThread: Use non-blocking reads from AudioRecord

---

app/build.gradle.kts
app/src/main/AndroidManifest.xml
app/src/main/java/com/chiller3/bcr/Notifications.kt
app/src/main/java/com/chiller3/bcr/OutputFile.kt
app/src/main/java/com/chiller3/bcr/Preferences.kt
app/src/main/java/com/chiller3/bcr/RecorderApplication.kt
app/src/main/java/com/chiller3/bcr/RecorderInCallService.kt
app/src/main/java/com/chiller3/bcr/RecorderProvider.kt
app/src/main/java/com/chiller3/bcr/RecorderThread.kt
app/src/main/java/com/chiller3/bcr/UriExtensions.kt
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-pl/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-sk/strings.xml
app/src/main/res/values-tr/strings.xml
app/src/main/res/values/strings.xml

This commit adds a new notification that fires when a call recording completes successfully. It's associated with a new notification channel so it can be disabled without affecting other notifications.
The notification has two action buttons: open and share. Both of these do as their name implies and do not dismiss the notification. Clicking on the notification text behaves like open, except the notification is dismissed.
The open and share options require a custom ContentProvider because it's not possible to grant the target app permissions to a SAF URI. BCR's RecorderProvider is very minimal and just wraps SAF's provider for the openFile, getType, and query operations.
Also, manual action from the user is required for the new open and share options to work. Previously, BCR only …

Send notification when a call recording completes

---

README.md

There's unfortunately nothing BCR can do for read-only filesystems. For those setups, Magisk is the best option.
Closes: #163

README.md: Add note about erofs volumes being read-only

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/chiller3/bcr/Notifications.kt
app/src/main/java/com/chiller3/bcr/RecorderInCallService.kt

Android's vibration setting seemingly has no effect when the user is in a phone call, which is always the case when a BCR notification is shown. With this commit, BCR will explicitly vibrate the device using a pattern that mimics what Android does by default for notifications.
This commit is inspired by @quyenvsp's PR #167, except it relies on Android notification channels' builtin vibration setting instead of adding a new setting to BCR.
Related PR: #167

Explicitly vibrate when vibration is enabled for a notification channel

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/chiller3/bcr/Permissions.kt
app/src/main/java/com/chiller3/bcr/RecorderThread.kt

This only works if all of these conditions are true:
* Android version is >= 11
* The user granted the `READ_PHONE_STATE` permission
* The device supports `FEATURE_TELEPHONY_SUBSCRIPTION`
* The device supports multiple SIMs
* There are currently multiple active SIMs
Fixes: #177

Add SIM slot ID to the filename if there are multiple active SIMs

---

app/src/main/java/com/chiller3/bcr/Notifications.kt

The intent for the "share" action is not distinguishable across notifications when compared with Intent.filterEquals() because they differ only in intent extras. This would cause the same PendingIntent to be reused for every share action, which would reference an old URI.
This commit fixes the issue by setting the ACTION_SEND data to the same value as the EXTRA_STREAM. The intent data is not used for this action, but makes the intent sufficiently unique that a PendingIntent won't be reused.

Fix broken share action due to PendingIntent reuse

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/chiller3/bcr/NotificationActionService.kt
app/src/main/java/com/chiller3/bcr/Notifications.kt
app/src/main/java/com/chiller3/bcr/OutputFile.kt
app/src/main/java/com/chiller3/bcr/RecorderInCallService.kt
app/src/main/java/com/chiller3/bcr/RecorderThread.kt
app/src/main/res/values/strings.xml

The new Delete action will show up alongside the current Open and Share actions, but unlike those other two actions, Delete will also dismiss the notification.
Fixes: #179

Add a new notification action for deleting the recording

---

app/src/main/res/xml/root_preferences.xml

There's no technical reason to disable these settings until call recording is enabled. It's even safe to change the settings while a recording is in progress.

Allow changing output settings while call recording is disabled

---

app/src/main/java/com/chiller3/bcr/RecorderThread.kt

The output filename variable was not initialized at the point that startLogcat() was called, resulting in an uninitialized property exception being thrown. This bug was introduced in commit 588d3f69b71a2b0691b0a0e29b397d32b7a8dd3f.
This commit also fixes startLogcat() accessing the filename property without acquiring the filenameLock lock. In practice, this did not cause issues, but better to be correct.
Discovered in issue #195.

RecorderThread: Fix silent crash when debug mode is enabled

---

app/src/main/java/com/chiller3/bcr/FilenameTemplate.kt
app/src/main/java/com/chiller3/bcr/RecorderThread.kt
app/src/main/res/raw/filename_template.properties

This commit adds support for specifying the timestamp pattern via the `${date:...}` syntax. For example, `${date:yyyyMMdd_HHmmss}`. Old files are not renamed; the user is responsible for doing so manually. If the user doesn't do so, the old files will likely be ignored by the file rentention cleanup process.
Implements: #204

Add support for custom timestamp patterns in the output filename

---

app/src/main/java/com/chiller3/bcr/RecorderThread.kt
app/src/main/res/values/strings.xml

There's nothing BCR can do if the device does not support call recording, so let's add a message about that when the exception stack trace involves `android.media.*` classes.

Add friendlier message when recording fails due to AudioRecord

---

app/src/main/java/com/chiller3/bcr/FilenameTemplate.kt

Matcher.appendReplacement() treats `\` and `$` specially, so we need to use Matcher.quoteReplacement() when passing in arbitrary strings.
Fixes: #207

FilenameTemplate: Fix potential crash when a variable's value contains `\` or `$`

---

app/src/main/java/com/chiller3/bcr/Notifications.kt
app/src/main/java/com/chiller3/bcr/RecorderInCallService.kt
app/src/main/java/com/chiller3/bcr/RecorderThread.kt
app/src/main/res/values/strings.xml

This commit implements basic pause/resume functionality via a notification action in BCR's persistent notification. Pausing is implemented by keeping the AudioRecord active, but discarding the data instead of passing it to the encoder. Pausing/resuming does not happen immediately, but after the processing of one buffer (which should be under 50ms on most devices). It's fast enough to be imperceptible.
Issue: #198

Add support for pausing/resuming the recording

---

app/src/main/java/com/chiller3/bcr/Preferences.kt
app/src/main/java/com/chiller3/bcr/RecorderInCallService.kt
app/src/main/java/com/chiller3/bcr/RecorderThread.kt
app/src/main/res/values/strings.xml
app/src/main/res/xml/root_preferences.xml

This commit adds a new "initially paused" option to BCR's UI. If it's disabled, then BCR works as it always has: calls are recorded as soon as they enter the connected state. If the option is enabled, then the recording starts in the paused state. The user can choose to resume via BCR's persistent notification. If the recording is never resumed, then the empty output file is deleted and no success notification will be shown.
This new option is disabled by default.
Issue: #198

Add new option for starting the recording in the paused state

---

app/src/main/res/values/strings.xml

Since we have separate strings for on/off states, I think it's best to tell user what _will_ happen in the current state, not what they can _tell_ us to do (subtle difference between imperative "start in the paused state" and "will be paused after starting").
#219 has the same wording now, and I thought the English version might use some changes as well.
The "on" description could also have the "displayed during a call" part, but this would get too long, wouldn't it?

Change "initially paused" preference description

---

app/src/main/res/values-sk/strings.xml

Signed-off-by: Peter Vágner <pvdeejay@gmail.com>

Update slovak language file

---

app/build.gradle.kts

This ensures that Magisk Manager will always show the correct changelog, without mentions of unreleased changes in the master branch.

app/build.gradle.kts: Update changelog link to point to the specific tag

---

README.md

After this commit, all further commits, tags, and release artifacts will be signed by a new SSH key:
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDOe6/tBnO7xZhAWXRj3ApUYgn+XZ0wnQiXM8B7tPgv4
To authenticate this change, this commit is signed with the existing GPG key (master key: `2233C479609BDCEC43BE9232F6A3B19090EFF32C`, subkey: `19C3E6E8FB86AD288B38AF2714200B173D8A3BF5`).
The reason for this change is to switch to stronger cryptography and also to rely on simpler tools that are readily available. SSH is already preinstalled on every desktop OS, including Windows.

Switch to signing via SSH key

---

app/src/main/java/com/chiller3/bcr/format/OpusFormat.kt

This reduces the number of steps from an excessive 253 steps to 25 steps.
Issue: #237

OpusFormat: Change step size from 2 kbps to 21 kbps

---

app/src/main/java/com/chiller3/bcr/OutputFormatBottomSheetFragment.kt

This fixes a crash due to `NoSuchMethodException` when switching to an output format that does not specify a parameter (bitrate or compression level). The workaround is no longer necessary now that the material3 bug has been fixed and we've upgraded to a release containing the fix in commit 3b0999ac1e3424047e44acf52efc2e17f7257415.
Fixes: #240

OutputFormatBottomSheetFragment: Remove workaround for material3 bug

---

app/src/main/java/com/chiller3/bcr/OutputDirUtils.kt
app/src/main/java/com/chiller3/bcr/RecorderApplication.kt
app/src/main/java/com/chiller3/bcr/RecorderThread.kt

This should help with troubleshooting when crashes occur outside of the scope of RecorderThread.
Issue: #243

Write crash log to output directory on uncaught exceptions

---

app/src/main/java/com/chiller3/bcr/Notifications.kt

This makes the pause/resume button more visible since high priority notifications are expanded by default (as long as it's the top notification). This only affects new installs and the user's configuration in Android's settings always has precedence.
Fixes: #248

Notifications.kt: Set persistent notifications' default priority to high

---

app/build.gradle.kts
app/magisk/customize.sh

Magisk currently has a known issue where its mirror mount points do not work correctly with overlayfs. Files from the overlayfs lowerdirs may no longer be accessible.
On MIUI, this is a problem because /system/etc/permissions is an overlayfs mount and one of the lowerdirs is
/product/pango/system/etc/permissions. One file underneath that path is com.nxp.nfc.nq.xml, which if missing, breaks NFC.
Fixes: #242
Fixes: #246

magisk: Try to install to a non-overlayfs location

---

app/build.gradle.kts
app/magisk/customize.sh

The update-binary expects the files to be in system/ for direct installation. This commit renames overlay/ back to system/ and adjusts customize.sh accordingly.
Fixes: #253

Fix direct installation

---

app/src/main/java/com/chiller3/bcr/DocumentFileExtensions.kt
app/src/main/java/com/chiller3/bcr/FilenameTemplate.kt
app/src/main/java/com/chiller3/bcr/RecorderThread.kt

As encountered in #252, some devices have a horrendous SAF implementation that takes upwards of 8 seconds just to check for the existence of `bcr.properties` in the output directory. The main cause of the delay is that the `DocumentFile.findFile()` implementation is very inefficient and performs a separate query to the document provider for each child in the directory. The first commit addresses this by reimplementing the method to use a single query.
However, even with the optimized query, it still takes >500ms on some devices, so the second commit updates `RecorderThread` to defer custom filename template processing until the end of the call.
To illustrate the absurdity of this slowness, when using native `File`s with the default output directory (no-SAF) on the same device, the same …

Improve SAF performance and defer custom filename template processing to the end of the call

---

app/src/main/java/com/chiller3/bcr/RecorderThread.kt

Otherwise, if the caller ID or contact name changes during the middle of the call, we might leak that information in the log file during rename.

RecorderThread: Never clear redactions

---

app/src/main/java/com/chiller3/bcr/DocumentFileExtensions.kt
app/src/main/java/com/chiller3/bcr/RecorderThread.kt

When `DocumentFile.renameTo()` is called on a SAF URI, the file extension is preserved, but this is not the case for file URIs. This commit introduces an extension method `.renameToPreserveExt()` that behaves the same regardless of URI.

Fix loss of filename extension due to `DocumentFile.renameTo()`

---

app/build.gradle.kts
app/proguard-rules.pro
app/src/main/java/com/chiller3/bcr/Preferences.kt
app/src/main/java/com/chiller3/bcr/RecorderThread.kt
app/src/main/java/com/chiller3/bcr/SettingsActivity.kt

We call it via reflection in our faster DocumentFile extensions and the first parameter was being optimized out in release builds because it is always null in the usages that R8 is able to analyze.
Related-to: #257
Fixes: #260

app/proguard-rules.pro: Keep TreeDocumentFile constructor

---

app/src/main/java/com/chiller3/bcr/Preferences.kt

`releasePersistableUriPermission()` can throw an undocumented exception when releasing a grant that was previously persisted if the URI's associated application is uninstalled. This commit changes the behavior to ignore exceptions when releasing persisted permissions. In every scenario I can reproduce where this function fails, the permission has already been removed by Android itself.

Preferences: Ignore releasePersistableUriPermission exceptions

---

app/src/main/java/com/chiller3/bcr/Permissions.kt
app/src/main/java/com/chiller3/bcr/RecorderInCallService.kt
app/src/main/java/com/chiller3/bcr/RecorderThread.kt
app/src/main/res/raw/filename_template.properties

* RecorderInCallService and RecorderThread have been updated to be aware of parent/child relationships of calls. Previously, child calls were treated as independent calls, so a conference call would result in separate (but identical in audio) recordings for the parent conference call and every call it was merged from.
* RecorderInCallService and RecorderThread now trim out sections of the recording where the call is in the HOLDING state. This prevents audio from a different call from being recorded while the call is on hold (due to call waiting).
* RecorderThread now performs a manual contact lookup if the Android telephony framework does not provide the contact display name. This is common in conference calls and is likely a bug in AOSP. As a side effect, contact lookup now works in all …

Improve conference call handling

---

app/src/main/java/com/chiller3/bcr/DocumentFileExtensions.kt

`MimeTypeMap`'s `getExtensionFromMimeType()` and `getMimeTypeFromExtension()` are not consistent with each other. Querying the extension for `audio/mp4` returns `m4a` as expected, but querying the MIME type for `m4a` returns `audio/mpeg`, which is associated with the `mp3` extension.
Due to this, whenever an output file needed to be renamed, files that originally had the `m4a` extension would get changed to `mp3`. This commit fixes the issue by removing the whole extension -> MIME type -> extension round trip when renaming files. Instead, it just appends everything after the last dot from the original filename when renaming.
Fixes: #292

DocumentFileExtensions.kt: Use simple string operations to preserve extension when renaming

---

app/build.gradle.kts

The method was deprecated in JDK 19. For uniqueness of the name given to ArchiveCommand.registerFormat(), we can just use the task name instead. Two instances of the same task will never run concurrently.
Issue: #294

app/build.gradle.kts: Avoid calling deprecated Thread.getId()

---

README.md
app/src/main/AndroidManifest.xml
app/src/main/java/com/chiller3/bcr/OutputFilenameGenerator.kt
app/src/main/java/com/chiller3/bcr/Permissions.kt
app/src/main/java/com/chiller3/bcr/Preferences.kt

This commit adds a new `{call_log_name}` variable that can be used in the filename template for including the call log cached name. The cache name may be updated by the system dialer to include the name of the business assocciated with the phone number.
This new variable is added to the default filename template, but only as a last resort because it relies on polling for up to 2 seconds after the call completes.
Fixes: #291

Add support for looking up the cached name in the call log

---

CHANGELOG.md
README.md
app/src/main/java/com/chiller3/bcr/OutputFilenameGenerator.kt

The two new added options are `digits_only` and `formatted` (country-specific style). These are the only two options that can be feasibly supported without pulling in something like libphonenumber.
Fixes: #290

Add support for some phone number formatting options

---

app/src/main/java/com/chiller3/bcr/FilenameTemplateDialogFragment.kt
app/src/main/java/com/chiller3/bcr/OutputDirectoryBottomSheetFragment.kt
app/src/main/java/com/chiller3/bcr/OutputFilenameGenerator.kt
app/src/main/java/com/chiller3/bcr/Template.kt
app/src/main/res/values/strings.xml
app/src/test/java/com/chiller3/bcr/TemplateTest.kt

Instead of performing a test evaluation, which can miss fallback choices, we instead query the entire template AST for all variable ref nodes. For each of the nodes, we check that both the name and argument are valid.
(The error messages have syntax highlighting too!)

Validate arguments when editing filename template

---

CHANGELOG.md
app/src/main/java/com/chiller3/bcr/FileRetentionDialogFragment.kt
app/src/main/java/com/chiller3/bcr/FilenameTemplateDialogFragment.kt
app/src/main/java/com/chiller3/bcr/FormatParamDialogFragment.kt
app/src/main/java/com/chiller3/bcr/OutputDirectoryBottomSheetFragment.kt
app/src/main/java/com/chiller3/bcr/OutputFormatBottomSheetFragment.kt
app/src/main/java/com/chiller3/bcr/Retention.kt
app/src/main/java/com/chiller3/bcr/SettingsActivity.kt
app/src/main/java/com/chiller3/bcr/format/AacFormat.kt
app/src/main/java/com/chiller3/bcr/format/FlacContainer.kt
app/src/main/java/com/chiller3/bcr/format/FlacFormat.kt
app/src/main/java/com/chiller3/bcr/format/Format.kt
app/src/main/java/com/chiller3/bcr/format/FormatParamInfo.kt
app/src/main/java/com/chiller3/bcr/format/OpusFormat.kt
app/src/main/java/com/chiller3/bcr/format/WaveContainer.kt
app/src/main/res/layout/dialog_text_input.xml
app/src/main/res/layout/output_directory_bottom_sheet.xml
app/src/main/res/layout/output_format_bottom_sheet.xml
app/src/main/res/values/strings.xml

Instead of using a slider with a min, max, and step size, the format parameter is configured using chips. For each format, there are three presets and there's an additional option for the user to set a specific compression level or bitrate. The user's existing settings will be preserved.
Fixes: #295

Replace format parameter slider with chips

---

README.md
app/build.gradle.kts
app/magisk/customize.sh
app/proguard-rules.pro
app/src/main/java/com/chiller3/bcr/standalone/RemoveHardRestrictions.kt

Since Android 10, READ_CALL_LOG has been marked as a hard-restricted permission, which prevents it from being granted by the user unless the app is given an exemption. There are three types of exemptions: system, upgrade, and installer.
System exemptions can be given by `/system/etc/default-permissions` (only on first boot) or via roles. Neither are usable for BCR. Upgrade exemptions are only given during Android OS upgrades that further restrict existing permissions. Installer exemptions are given by whichever app installs another app, but there's no installer when it comes to adding new system apps, like BCR.
Since AOSP has no sane built-in way to exempt BCR from the hard restriction, we'll do it ourselves. This commit introduces a new CLI utility baked in BCR that will talk to …

Work around READ_CALL_LOG being hard-restricted

---

app/src/main/res/values-ru/strings.xml

Tell me, is it possible to combine these 2 lines with this 1 argument?
Now
`<string name="output_dir_bottom_sheet_filename_template">Шаблон имени файла</string>`
`<string name="filename_template_dialog_title">Шаблон имени файла</string>`
After
`<string name="output_dir_bottom_sheet_filename_template">Шаблон имени файла</string>`
`<string name="filename_template_dialog_title">@string/output_dir_bottom_sheet_filename_template</string>`
Or is it not possible to do this for the title?

Russiano #2

---

app/build.gradle.kts
app/magisk/boot_common.sh
app/magisk/post-fs-data.sh
app/magisk/service.sh
app/src/main/java/com/chiller3/bcr/standalone/ClearPackageManagerCaches.kt
app/src/main/java/com/chiller3/bcr/standalone/RemoveHardRestrictions.kt

On some devices, the system time is set too late in the boot process. This, for some reason, causes the package manager service to not update the cache entry in /data/system/package_cache despite the mtime of the apk being newer than the mtime of the cache entry [1]. The outdated cache entry causes BCR to crash with an error about the app theme not being derived from Theme.AppCompat. This commit works around the issue in a brute force way by deleting BCR's package manager cache entry on every boot.
[1] https://cs.android.com/android/platform/superproject/+/android-13.0.0_r42:frameworks/base/services/core/java/com/android/server/pm/parsing/PackageCacher.java;l=139
Fixes: #275, #303, #307

Clean package manager caches on boot

---

app/src/main/java/com/chiller3/bcr/Notifications.kt
app/src/main/java/com/chiller3/bcr/OutputFilenameGenerator.kt
app/src/main/java/com/chiller3/bcr/RecorderInCallService.kt
app/src/main/java/com/chiller3/bcr/RecorderThread.kt
app/src/main/res/values/strings.xml

This makes the current state more visible to the user when using call waiting and allows the pause/resume state to be handled correctly. This also adds the filename to the notification text.

Show a separate persistent notification for each call

---

CHANGELOG.md
app/build.gradle.kts

When adding new changelog entries, we just need to type `[Issue #0]` or `[PR #0 @user]` and then run `./gradlew changelogUpdateLinks`, which will automatically update the link references at the bottom of the file.

Make changelog links clickable

---

app/src/main/java/com/chiller3/bcr/Preferences.kt
app/src/main/java/com/chiller3/bcr/RecorderApplication.kt
app/src/main/java/com/chiller3/bcr/template/Template.kt
app/src/test/java/com/chiller3/bcr/template/TemplateTest.kt

This was planned for removal in version 1.45.

Remove bcr.properties to filename template migration logic

---

app/src/main/java/com/chiller3/bcr/RecorderApplication.kt
app/src/main/java/com/chiller3/bcr/RecorderInCallService.kt
app/src/main/java/com/chiller3/bcr/RecorderThread.kt
app/src/main/java/com/chiller3/bcr/dialog/FilenameTemplateDialogFragment.kt
app/src/main/java/com/chiller3/bcr/extension/DocumentFileExtensions.kt
app/src/main/java/com/chiller3/bcr/output/OutputDirUtils.kt
app/src/main/java/com/chiller3/bcr/output/OutputFilenameGenerator.kt
app/src/main/java/com/chiller3/bcr/settings/OutputDirectoryBottomSheetFragment.kt
app/src/main/java/com/chiller3/bcr/template/TemplateSyntaxHighlighter.kt
app/src/main/res/layout/dialog_text_input.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml

This commit adds support for using directory separators `/` in the filename template. The separators are only allowed in the parts of the template controlled by the user (eg. outside of variables or inside the `${date:<arg>}` argument). If the separator appears in any other variable, like the caller ID, it is replaced with an underscore. While `.` and
`..` are properly handled in AOSP's `FileSystemProvider` (the default `DocumentsProvider` used when the user selects a directory on the internal storage or SD card), BCR will silently omit these path segments to avoid potential security issues when a 3rd party cloud app output directory is chosen.
All existing features are supported when subdirectories are used, including the file retention feature. However, due to the absurd slowness of …

Add support for directory separators in the filename template

---

app/src/main/java/com/chiller3/bcr/RecorderTileService.kt
app/src/main/java/com/chiller3/bcr/settings/SettingsFragment.kt

Fixes #376, hope I did it right.
For full API 34 compatibility the following should be fixed: <https://developer.android.com/reference/kotlin/android/service/quicksettings/TileService#startactivityandcollapse_1>
`fun startActivityAndCollapse(intent: Intent!): Unit` is deprecated in favor of `fun startActivityAndCollapse(pendingIntent: PendingIntent): Unit`

Fixes to compile under SDK 34

---

app/src/main/java/com/chiller3/bcr/Preferences.kt
app/src/main/java/com/chiller3/bcr/extension/UriExtensions.kt
app/src/main/java/com/chiller3/bcr/settings/SettingsFragment.kt
app/src/main/res/values/strings.xml
app/src/main/res/xml/root_preferences.xml

Long pressing the output directory preference will open the file manager. This normally uses DocumentsUI, but if any 3rd party file manager supports receiving intents with the `vnd.android.document/directory` type, then the user will be able to choose from the system or 3rd party file manager.
Issue: #135

Add shortcut for opening the output directory in DocumentsUI

---

app/src/main/java/com/chiller3/bcr/NotificationActionService.kt

Otherwise, an Intent from a previous PendingIntent with the same notification ID might be used, causing the wrong file to be deleted.

NotificationActionService: PendingIntent needs to be unique across app restarts

---

app/src/main/java/com/chiller3/bcr/RecorderTileService.kt

`java.lang.NullPointerException: Attempt to invoke virtual method 'void android.service.quicksettings.Tile.setState(int)' on a null object reference`
I'm not absolutely sure if I did it right. This random crash is extremely rare (one on a few weeks/months) and it's not related to any activity, it did never happen while recording.
Probably this PR might improve code safety as a side effect too. ;)

Prevent very rare crash due to NullPointerException

---

app/src/main/java/com/chiller3/bcr/NotificationActionService.kt

This is caused by an upstream Android 13 bug that will only be fixed in Android 14 onwards.
https://issuetracker.google.com/issues/274185314
Fixes: #388

Work around Intent.getParcelableArrayListExtra() crash on Android 13

---

app/src/main/java/com/chiller3/bcr/Notifications.kt
app/src/main/java/com/chiller3/bcr/Preferences.kt
app/src/main/java/com/chiller3/bcr/RecorderInCallService.kt

When Android kills and relaunches BCR, old notifications may not be cleared. This could cause unexpected behavior if a notification ID is reused.

Persist next notification ID in the shared preferences

---

app/src/main/java/com/chiller3/bcr/output/OutputFilenameGenerator.kt

OutputFilenameGenerator: Add missing return keyword when getting `direction` variable

---

gradle/verification-metadata.xml

There's no sane way to add the checksums for these in the metadata file and they don't get compiled into the final binary anyway. This fixes API documentation and source code not showing up in Android Studio. This is gradle's recommended workaround for this issue [1].
[1] https://docs.gradle.org/current/userguide/dependency_verification.html#sec:skipping-javadocs

Disable gradle verification for sources and javadocs jars

---

app/src/main/java/com/chiller3/bcr/dialog/FileRetentionDialogFragment.kt
app/src/main/java/com/chiller3/bcr/dialog/FilenameTemplateDialogFragment.kt
app/src/main/java/com/chiller3/bcr/dialog/FormatParamDialogFragment.kt
app/src/main/java/com/chiller3/bcr/dialog/MessageDialogFragment.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-pl/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-tr/strings.xml
app/src/main/res/values-uk/strings.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values-zh-rTW/strings.xml
app/src/main/res/values/strings.xml

OK and Cancel are already defined in [Android resources](https://developer.android.com/reference/android/R.string), so no need for custom implementation and maintaining translations of them.

Standardize OK and Cancel buttons; use defined in Android resources

---

app/src/main/res/values-pl/strings.xml

Sync, update and fix (typo) Polish translation.

Sync, update and fix Polish translation

---

app/magisk/update-binary

The source field for dm-linear block devices in the recovery's fstab is not an actual file path.
Fixes: #338

module: Try to explicitly mount dm-linear block devices

---

app/src/main/java/com/chiller3/bcr/Permissions.kt
app/src/main/java/com/chiller3/bcr/settings/SettingsFragment.kt

Currently, BCR will just gray out the `Disable battery optimization` option after it is enabled because Android does not provide a way for apps to re-enable optimizations.
This isn't very user-friendly, so this commit updates the option to never be grayed out, but instead, take the user to the appropriate page in Android's Settings.
Fixes: #422

Launch Android Settings to re-enable battery optimization

---

README.md
app/src/main/java/com/chiller3/bcr/output/CallMetadataCollector.kt
app/src/main/java/com/chiller3/bcr/output/PhoneNumber.kt

Android 10 added the `CallRedirectionService` API, which allows a third party app to process outgoing calls made from the system's dialer. Some call redirection services, like Google Voice, use phone calls under the hood instead of VOIP. These calls can be recorded by BCR, but would previously show the service's proxy phone number.
Unfortunately, with the way Android's APIs are designed, the only thing that's aware of the original phone number is the dialer. We have no way of querying that in BCR until the call ends and the dialer writes the entry to the call log. This commit implements support for looking up the phone number from the call log.
This lookup functionality only works for non-conference calls and the call will always be classified as `All other calls` in the auto-record …

Add limited support for call redirection

---

app/src/main/AndroidManifest.xml

While BCR itself has no native code, the system media codecs do and we've run into memory corruption issues in the past (eg. the FLAC encoder can sometimes segfault if audio buffer timestamps are not set correctly).
Enabling MTE won't really make a difference security-wise for BCR. We never parse any untrusted inputs. But it might help catch potential issues in the media stack.

Enable memory tagging extensions for ARMv9 devices

---

README.md
app/build.gradle.kts
app/src/main/res/values-hi/strings.xml
app/src/main/res/xml/locales_config.xml

added hindi translation strings.xml

added hindi translation strings.xml

---

app/build.gradle.kts
app/src/main/res/values-it/strings.xml
app/src/main/res/xml/locales_config.xml

Added italian strings

---

app/src/main/java/com/chiller3/bcr/IoHelpers.kt
app/src/main/java/com/chiller3/bcr/RecorderThread.kt
app/src/main/java/com/chiller3/bcr/dialog/FormatParamDialogFragment.kt
app/src/main/java/com/chiller3/bcr/format/AmrContainer.kt
app/src/main/java/com/chiller3/bcr/format/AmrNbFormat.kt
app/src/main/java/com/chiller3/bcr/format/AmrWbFormat.kt
app/src/main/java/com/chiller3/bcr/format/FlacContainer.kt
app/src/main/java/com/chiller3/bcr/format/Format.kt
app/src/main/java/com/chiller3/bcr/format/FormatParamInfo.kt
app/src/main/java/com/chiller3/bcr/format/WaveContainer.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-hi/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-iw/strings.xml
app/src/main/res/values-pl/strings.xml
app/src/main/res/values-pt-rPT/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-sk/strings.xml
app/src/main/res/values-tr/strings.xml
app/src/main/res/values-uk/strings.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values-zh-rTW/strings.xml
app/src/main/res/values/strings.xml

The patents have now expired everywhere in North America and Europe.
Note that this is not dumping the raw AMR call audio stream, which is impossible on Android. The audio goes from AMR -> PCM -> AMR so the output is a lossy reencoding. Users who want lossless recordings should stick with FLAC or WAV.
Closes: #264
[1] https://voiceage.com/Patent-Portfolio.html
[2] https://voiceage.com/Patent-Portfolio-Essential.html
[3] https://patents.google.com/patent/EP1354315B1/es
[4] https://brevets-patents.ic.gc.ca/opic-cipo/cpd/eng/patent/2423651/summary.html

Add support for AMR-WB and AMR-NB

---

app/src/main/java/com/chiller3/bcr/Contact.kt
app/src/main/java/com/chiller3/bcr/RecorderThread.kt
app/src/main/java/com/chiller3/bcr/extension/CallDetailsExtensions.kt
app/src/main/java/com/chiller3/bcr/output/CallMetadataCollector.kt
app/src/main/java/com/chiller3/bcr/output/PhoneNumber.kt
app/src/main/java/com/chiller3/bcr/rule/RecordRule.kt

Otherwise, performing a contact lookup will fail with an obscure error due to a missing path component in the lookup URI.
Fixes: #455

PhoneNumber: Do not allow empty strings

---

app/build.gradle.kts
app/src/main/java/com/chiller3/bcr/dialog/FormatSampleRateDialogFragment.kt
app/src/main/java/com/chiller3/bcr/extension/AudioFormatExtensions.kt
app/src/main/java/com/chiller3/bcr/format/AacFormat.kt
app/src/main/java/com/chiller3/bcr/format/AmrNbFormat.kt
app/src/main/java/com/chiller3/bcr/format/AmrWbFormat.kt
app/src/main/java/com/chiller3/bcr/format/FlacFormat.kt
app/src/main/java/com/chiller3/bcr/format/Format.kt
app/src/main/java/com/chiller3/bcr/format/OpusFormat.kt
app/src/main/java/com/chiller3/bcr/format/SampleRateInfo.kt
app/src/main/java/com/chiller3/bcr/format/WaveFormat.kt
app/src/main/java/com/chiller3/bcr/settings/OutputFormatBottomSheetFragment.kt
app/src/main/res/values-tr/strings.xml
app/src/main/res/values/strings.xml

Some devices unfortunately disable common sample rates that are normally supported in AOSP's software encoders. This commit reworks all of BCR's MediaCodec-based formats to query for the list of supported sample rates instead of relying on a hardcoded list. If BCR's default sample rate for a format is not supported, the closest supported sample rate will be used. The same applies for Android upgrades that remove support for the sample rate previously chosen by the user.
These queries are fast enough to be unnoticeable on Pixel devices. Hopefully other OEMs don't make modifications that slow this down, like they do for so many other things.
Fixes: #507

Automatically detect supported sample rates for each codec

---

app/src/main/java/com/chiller3/bcr/output/CallMetadataCollector.kt

CallMetadataCollector: getActiveSubscriptionInfo() can return null

---

app/src/main/java/com/chiller3/bcr/Preferences.kt
app/src/main/java/com/chiller3/bcr/RecorderInCallService.kt
app/src/main/res/values/strings.xml
app/src/main/res/xml/root_preferences.xml

BCR records from the VOICE_CALL audio stream, which only works with plain old phone calls. Recording calls from telecom-integrated apps will likely only produce pure silence.
The recording of these calls is turned off by default to avoid producing useless recordings.
Issue: #513

Make recording calls from telecom-integrated apps optional

---

app/src/main/java/com/chiller3/bcr/RecorderThread.kt
app/src/main/res/values/strings.xml

Completely silent, in this context, means that every buffer received from the audio driver consisted entirely of zeros. There is no point in saving these files because they do not contain any useful audio.
Issue: #513

Discard recordings that are completely silent

---

app/src/main/res/values-it/strings.xml

Fixed
```xml
<string name="record_rule_type_all_other_calls_name">Tuttle le altre chiamate</string>
```
to
```xml
<string name="record_rule_type_all_other_calls_name">Tutte le altre chiamate</string>
```
~tuttle~ --> tutte (all)

Fixed it-IT translation typo

---

app/build.gradle.kts
app/src/main/AndroidManifest.xml
app/src/main/java/com/chiller3/bcr/extension/AudioFormatExtensions.kt

Some custom Android builds seem to have a bug where the sysconfig file is not respected for some boots.
Fixes: #539
Fixes: #546

Use android:usesNonSdkApi to access hidden/system APIs

---

CHANGELOG.md
app/src/main/java/com/chiller3/bcr/rule/RecordRulesFragment.kt
app/src/main/java/com/chiller3/bcr/rule/RecordRulesViewModel.kt

BCR can potentially be unloaded from memory when the user is in Android's contact picker activity. If this happens, when they return, the coroutines in `refreshRules()` and `addContactRule()` may execute at the same time. This does not cause crashes due to `MutableStateFlow`'s compare and set behavior, but does cause weird behavior, like the new contact rule being added to an empty list of rules.
Fixes: #554

RecordRulesViewModel: Fix race condition when mutating rules

---

app/src/main/res/xml/root_preferences.xml

The persistent value is never read because the actual state is controlled by Android.

root_preferences.xml: inhibit_batt_opt should not be persistent

---

app/build.gradle.kts
app/magisk/customize.sh

LineageOS Updater falsely executes overlayed addon.d scripts for A/B partitioned devices during OTA.
It causes the Magisk modules' patched system files to be copied to the real system partition.
We need to delete our addon.d script when installing as Magisk module.

Delete addon.d script when installing as Magisk module

---

app/src/main/java/com/chiller3/bcr/standalone/ClearPackageManagerCaches.kt
app/src/main/java/com/chiller3/bcr/standalone/RemoveHardRestrictions.kt

This makes it possible for these tools to be run from an init script without losing the output. There is no impact to the Magisk scripts since the logcat output is captured there anyway.

standalone: Log output to logcat

---

app/magisk/update-binary

There are devices using A/B with static partitions. Since the `ro.boot.slot_suffix` property is unset on non-A/B devices, we can just always append it to the block device name.
Fixes: #569

update-binary: Add support for A/B devices using static partitions

---

README.md
app/src/main/AndroidManifest.xml
app/src/main/java/com/chiller3/bcr/DirectBootMigrationReceiver.kt
app/src/main/java/com/chiller3/bcr/DirectBootMigrationService.kt
app/src/main/java/com/chiller3/bcr/Notifications.kt
app/src/main/java/com/chiller3/bcr/Preferences.kt
app/src/main/java/com/chiller3/bcr/RecorderApplication.kt
app/src/main/java/com/chiller3/bcr/RecorderInCallService.kt
app/src/main/java/com/chiller3/bcr/RecorderThread.kt
app/src/main/java/com/chiller3/bcr/RecorderTileService.kt
app/src/main/java/com/chiller3/bcr/extension/DocumentFileExtensions.kt
app/src/main/java/com/chiller3/bcr/extension/UriExtensions.kt
app/src/main/java/com/chiller3/bcr/output/OutputDirUtils.kt
app/src/main/java/com/chiller3/bcr/output/OutputFilenameGenerator.kt
app/src/main/java/com/chiller3/bcr/settings/SettingsFragment.kt
app/src/main/res/values/strings.xml
app/src/main/res/xml/root_preferences.xml

This allows BCR to record calls prior to the device being initially unlocked after a reboot. In the BFU (before unlock state), recordings are temporarily stored in an internal device-protected storage directory. If the call completes before the initial unlock, then a migration service that automatically runs after unlock will move the files to the output directory. If the device is unlocked while the call is still ongoing, then the recording will be moved to the output directory at the end of the call.
There are some limitations, like not being able to look up contacts or the call log, but most of BCR's will basically work as expected.

Add support for direct boot

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/chiller3/bcr/DirectBootMigrationReceiver.kt
app/src/main/java/com/chiller3/bcr/DirectBootMigrationService.kt
app/src/main/res/values/strings.xml

There seem to be two issues with the foreground service:
* Some Android builds seem to be broken and throw a ForegroundServiceDidNotStartInTimeException even though the service unconditionally calls startForeground() in onStartCommand(). The root cause of this is unknown. Perhaps these devices are exceptionally slow during boot?
* The persistent notification does not get dismissed when the file migration runs too quickly.
We may be able to work around the second issue by not setting the FOREGROUND_SERVICE_IMMEDIATE notification behavior flag, but given how fast the file migration is, let's just switch to a background service. We're unlikely to hit Android's limitations on background services.
Closes: #574
Closes: #576

Switch DirectBootMigrationService to a background service

---

app/src/main/java/com/chiller3/bcr/settings/SettingsFragment.kt

SettingsFragment was still trying to start the service as a foreground service. This was overlooked in 17f6d19f65317b3f36b1a2329cca03a2f5cca22b.

Fix manually triggering direct boot file migration via debug settings

---

app/src/main/java/com/chiller3/bcr/Notifications.kt
app/src/main/java/com/chiller3/bcr/RecorderInCallService.kt
app/src/main/java/com/chiller3/bcr/RecorderThread.kt
app/src/main/res/values/strings.xml

The warning can sometimes be triggered when hanging up before the other party is able to answer, so allow the user to disable the notification if desired.
This commit also changes the recorder thread status reporting to be more explicit and type-safe. All user-facing error messages are now computed in the UI layers instead of the recorder thread.
Closes: #579

Split pure silence warning notification to separate channel

---

app/magisk/post-fs-data.sh
app/magisk/service.sh

OxygenOS on OnePlus devices seems to create the `/data/user_de/0/<id>` directory with the wrong SELinux label initially. However, once the correct label is set, it persists just fine. Despite it persisting, we still need to run restorecon during boot instead of during installation because it requires PackageManager to already be aware of BCR.
Fixes: #582
Fixes: #591
Fixes: #598

service.sh: Restore SELinux labels on DP data directory during boot

---

app/src/main/java/com/chiller3/bcr/Notifications.kt

This fixes success notifications not showing when using the default output directory. `relativeToOrNull()` can include `../` components, so it's not suitable for the job. The boolean operator was also incorrect.

Notifications: Fix isDeviceProtectedStorage() check

---

app/src/main/java/com/chiller3/bcr/Preferences.kt
app/src/main/java/com/chiller3/bcr/RecorderInCallService.kt
app/src/main/java/com/chiller3/bcr/RecorderThread.kt
app/src/main/java/com/chiller3/bcr/dialog/MinDurationDialogFragment.kt
app/src/main/java/com/chiller3/bcr/settings/SettingsFragment.kt
app/src/main/res/values/strings.xml
app/src/main/res/xml/root_preferences.xml

If the recording isn't long enough, it will be discarded at the end of the call. The duration is computed based on the recording duration (number of encoded frames), not the call duration, so it excludes regions where the user explicitly paused the recording and regions where the call was placed on hold.
Similar to the record rules, this can be overridden during the call from BCR's notification.
Fixes: #411
Fixes: #604

Add support for specifying a minimum recording duration

---

app/src/main/java/com/chiller3/bcr/extension/CursorExtensions.kt
app/src/main/java/com/chiller3/bcr/extension/DocumentFileExtensions.kt

The original idea was fundamentally not workable. Nothing would cause the `use { ... }` block to end immediately after we stop consuming the iterator. I'm too used to languages with RAII.

DocumentFileExtensions: Fix Cursor resource leak

---

app/src/main/java/com/chiller3/bcr/Notifications.kt

We don't use a different expanded notification message, so the default behavior is sufficient.

Notifications: Avoid overriding expanded notification text

---

app/build.gradle.kts
app/src/main/res/values-ro/strings.xml
app/src/main/res/xml/locales_config.xml

First of all thanks for the app, it is an option for call recording even without root.
I am new to this but want to help to develop the app. I have inserted the translation into the file ‎app/src/main/res/values-ro/strings.xml. I also updated the app/src/main/res/xml/locales_config.xml and app/build.gradle.kts files.
If I got something wrong, let me know.

Romanian (ro) translate

---

app/src/main/java/com/chiller3/bcr/rule/PickContactGroupAlert.kt
app/src/main/java/com/chiller3/bcr/rule/PickContactGroupFragment.kt
app/src/main/java/com/chiller3/bcr/rule/PickContactGroupViewModel.kt
app/src/main/java/com/chiller3/bcr/rule/RecordRulesViewModel.kt
app/src/main/res/values/strings.xml

PickContactGroupFragment: Show error in snackbar if query fails

---

app/src/main/java/com/chiller3/bcr/Contact.kt
app/src/main/java/com/chiller3/bcr/rule/PickContactGroupFragment.kt
app/src/main/java/com/chiller3/bcr/rule/PickContactGroupViewModel.kt
app/src/main/java/com/chiller3/bcr/rule/RecordRule.kt
app/src/main/java/com/chiller3/bcr/rule/RecordRulesFragment.kt
app/src/main/java/com/chiller3/bcr/rule/RecordRulesViewModel.kt
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ro/strings.xml
app/src/main/res/values/strings.xml

Android does not require accounts to set the SOURCE_ID for groups. This previously caused the group list query to fail, leading to an empty contact group picker screen.
Fixes: #620

Contact.kt: The SOURCE_ID for groups is allowed to be null

---

app/src/main/java/com/chiller3/bcr/format/SampleRateInfo.kt

Android OEMs are such garbage. This was already fixed in AOSP 6 years ago.
https://android.googlesource.com/platform/frameworks/base/+/2e961480fe0f4e87f2b7f621b276035864124f69%5E%21/
Fixes: #628

SampleRateInfo: Work around NullPointerException on older OS's

---

app/build.gradle.kts
app/src/main/java/com/chiller3/bcr/extension/AudioFormatExtensions.kt

Older versions of Android 9 are missing the the AOSP commit that added support for android:usesNonSdkApi.
https://android.googlesource.com/platform/frameworks/base/+/ca6f81d39525174e926c2fcc824fe9531ffb3563%5E%21/
This partially reverts commit 9823a982c0bb1948e22bcc80886dba656988a986.
Fixes: #628

Use sysconfig file in addition to android:usesNonSdkApi

---

app/src/main/java/com/chiller3/bcr/DirectBootMigrationService.kt
app/src/main/java/com/chiller3/bcr/extension/DocumentFileExtensions.kt
app/src/main/java/com/chiller3/bcr/extension/MimeTypeMapExtensions.kt
app/src/main/java/com/chiller3/bcr/extension/UriExtensions.kt
app/src/main/java/com/chiller3/bcr/output/OutputDirUtils.kt

Android 9 and 10 support a much smaller list of MIME types because they hadn't migrated to the mime-support package yet (used by most Linux distros). With this commit, BCR will explicitly append the file extension for `audio/mp4` when saving to local storage. Other document providers don't get this special treatment because there is no way to determine which MIME types they support.

Manually handle audio/mp4 file extension in older versions of Android

---

app/src/main/java/com/chiller3/bcr/output/CallMetadataCollector.kt
app/src/main/java/com/chiller3/bcr/rule/RecordRule.kt

This regressed after de0bd10c49e58f5ab6e9c7a0948a79bd1d2e3d5e, which turned null `Cursor` return values from `ContentResolver` queries into exceptions.
This updates the CallMetadataCollector (and RecordRule) queries to catch exceptions when querying contacts.
Fixes: #643

Fix crash when contact query fails in direct boot mode

---

app/src/main/java/com/chiller3/bcr/Preferences.kt
app/src/main/java/com/chiller3/bcr/RecorderApplication.kt
app/src/main/java/com/chiller3/bcr/settings/SettingsFragment.kt

This was originally planned for version 1.65, so it's quite overdue.

Remove migration for the legacy global sample rate option

---

app/src/main/java/com/chiller3/bcr/output/CallMetadataCollector.kt
app/src/main/java/com/chiller3/bcr/rule/RecordRuleEditorBottomSheet.kt

OxygenOS doesn't advertise support for it, but supports it anyway. Let's just assume that all Android versions capable of supporting SubscriptionManager actually support it. AOSP's Settings app doesn't check for this feature either.
Fixes: #649

Remove check for FEATURE_TELEPHONY_SUBSCRIPTION

---

app/src/main/res/values-iw/strings.xml

Thank you very much for the great app

Update Hebrew translation

---

README.md
app/src/main/java/com/chiller3/bcr/Preferences.kt
app/src/main/java/com/chiller3/bcr/RecorderThread.kt
app/src/main/java/com/chiller3/bcr/output/CallMetadata.kt

This measures the total wall time from when the recording started to when the recording ended. If this is significantly higher than the actual duration of the recording, then Android is failing to send the correct amount of audio to BCR.

Add wall duration to metadata JSON file
