chenxiaolong/BCR

app/src/main/java/com/chiller3/bcr/RecorderThread.kt

This only works on Android 10+.
Issue: #3

RecorderThread: Add incoming/outgoing tag to filenames

---

app/magisk/updates/release/changelog.txt
app/src/main/java/com/chiller3/bcr/CodecBottomSheetFragment.kt

CodecBottomSheetFragment: Fix resetting parameter value when default codec is selected

---

app/magisk/updates/release/changelog.txt
app/src/main/AndroidManifest.xml
app/src/main/java/com/chiller3/bcr/RecorderInCallService.kt
app/src/main/java/com/chiller3/bcr/RecorderThread.kt

This is not enabled by default and there's no user interface for
enabling it. The user can only enable the feature by manually going to
the system settings and enabling the Contacts permission for BCR.
Issue: #28

Add contact name to output filename

---

README.md

README.md: Add latest release and license badges

---

app/src/main/res/values-tr/strings.xml

Update tr translation

---

app/src/main/java/com/chiller3/bcr/RecorderThread.kt

RecorderThread.kt: Set priority to THREAD_PRIORITY_URGENT_AUDIO

---

app/build.gradle.kts

* `androidx.appcompat:appcompat`: 1.4.1 -> 1.4.2
* `androidx.core:core-ktx`: 1.7.0 -> 1.8.0
* `com.google.android.material:material`: 1.6.0 -> 1.6.1

build.gradle.kts: Update all dependencies

---

app/src/main/res/values-pl/strings.xml

Create strings.xml | Update polish translations

---

app/magisk/updates/release/changelog.txt
app/src/main/res/values-tr/strings.xml

Add "output directory bottom sheet" translations

Turkish update

---

app/magisk/update-binary

update-binary: Also perform a direct install if /system/bin/recovery exists

---

app/build.gradle.kts

Add addon.d script for LineageOS-based firmware

---

app/src/main/java/com/chiller3/bcr/RecorderThread.kt

The buffer size of `logcat -d` may not be enough to preserve all of the logs.
Issue: #143

RecorderThread: Run logcat for the duration of the recording

---

app/src/main/res/values-ru/strings.xml
app/src/main/res/values-tr/strings.xml

Update to Turkish and Russian translations

---

README.md

README.md: Document hidden/advanced features

---

app/src/main/res/values-iw/strings.xml

Hi, i added hebrew strings for your project.

Add hebrew translate

---

app/src/main/AndroidManifest.xml

Same as in #269 but for call recording.

a11y: mark quick settings tyle as toggleable

---

app/build.gradle.kts
app/src/main/AndroidManifest.xml
app/src/main/res/xml/locales_config.xml

Ads support for changing language of BCR's interface via system settings on Android 13+.

Add support for per-app language preferences

---

app/build.gradle.kts
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/xml/locales_config.xml

This software is very simple and easy to use, but it does not have Chinese language support, so I added a Chinese translation.

Add Simplified Chinese translation.

---

app/src/main/res/values-tr/strings.xml

The values on res/values/strings.xml were taken and added in their original order and translated into Turkish.

Translated some Turkish strings

---

app/src/main/res/values-ru/strings.xml

Added the item "Call on Hold", and also corrected the text in some places.

Russiano #3

---

app/src/main/res/values-ru/strings.xml

Adding untranslated strings for auto record rules from the issue #327

Russiano #4

---

CHANGELOG.md
app/build.gradle.kts

This commit also adds checks to the changelogUpdateLinks gradle task to ensure that it fails when invalid links are found.

CHANGELOG.md: Fix invalid links

---

app/src/main/java/com/chiller3/bcr/RecorderApplication.kt
app/src/main/java/com/chiller3/bcr/RecorderThread.kt
app/src/main/java/com/chiller3/bcr/output/OutputDirUtils.kt

This fixes a regression in #361, which reintroduced #292/#293.
Fixes: #367

Explicitly specify MIME type when moving files

---

app/build.gradle.kts
build.gradle.kts
gradle/libs.versions.toml

According to <https://developer.android.com/build/migrate-to-catalogs>

Migrate to Version Catalogs

---

README.md
app/src/main/java/com/chiller3/bcr/RecorderThread.kt

RecorderThread: Write output format and encoding info to metadata file

---

README.md
app/src/main/java/com/chiller3/bcr/output/OutputFilenameGenerator.kt

OutputFilenameGenerator: Add support for {sim_slot:always}

---

app/src/main/res/values-iw/strings.xml

Translation update to the Hebrew language

Update strings.xml Hebrew language

---

app/src/main/java/com/chiller3/bcr/RecorderThread.kt

This is more user-friendly since it doesn't require the user to manually enable debug mode and then try to reproduce the error.

RecorderThread: Always preserve logcat on errors

---

app/src/main/java/com/chiller3/bcr/standalone/RemoveHardRestrictions.kt

Android 14 QPR2 changed the internal API to add a new `deviceId` parameter.
https://android.googlesource.com/platform/frameworks/base/+/0f245abca17af3641fdd116ae079ca31c1569684%5E%21/

RemoveHardRestrictions: Add support for Android 14 QPR2

---

app/build.gradle.kts

Fix missing sysconfig file in build.gradle.kts

---

app/build.gradle.kts
app/src/main/res/values-ja/strings.xml
app/src/main/res/xml/locales_config.xml

Hello. Added Japanese translation.

Add Japanese translation

---

app/src/main/java/com/chiller3/bcr/standalone/RemoveHardRestrictions.kt

Android 14 QPR3 replaced the integer device ID parameter with a String persistent device ID parameter.
https://android.googlesource.com/platform/frameworks/base/+/7d7a26e18cced0411eb48d6c9413e98731b99faf%5E!/

RemoveHardRestrictions: Add support for Android 14 QPR3

---

README.md
app/src/main/java/com/chiller3/bcr/Preferences.kt
app/src/main/java/com/chiller3/bcr/RecorderInCallService.kt
app/src/main/res/values/strings.xml
app/src/main/res/xml/root_preferences.xml

Add option to start recording when a call is in the DIALING state

---

app/src/main/res/values-fr/strings.xml

Update strings.xml fr-FR

---

app/src/main/java/com/chiller3/bcr/Contact.kt
app/src/main/java/com/chiller3/bcr/output/CallMetadataCollector.kt
app/src/main/java/com/chiller3/bcr/rule/PickContactGroupViewModel.kt
app/src/main/java/com/chiller3/bcr/rule/RecordRule.kt
app/src/main/java/com/chiller3/bcr/rule/RecordRulesViewModel.kt

Same fix as for `DocumentFileExtensions.kt` in 5620fbb49893cefcbb0cea5d91a46d071a6a1229.

Contact.kt: Fix Cursor resource leak

---

app/src/main/res/values-fr/strings.xml

Update fr-FR translation for v1.73

Update FR strings

---

app/src/main/java/com/chiller3/bcr/output/OutputFilenameGenerator.kt

If creating a file goes through MediaProvider's FUSE mount and a path component contains one of these disallowed code points, then the file creation will fail with `EPERM`.
Fixes: #691
Co-authored-by: @TheDeathDragon

OutputFilenameGenerator: Replace FAT32-invalid and ignorable code points
